# Generated by Django 5.0 on 2023-12-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('logadouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('locaclidade', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
    ]
