# Generated by Django 5.0 on 2023-12-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cep_lookup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cep',
            old_name='locaclidade',
            new_name='localidade',
        ),
    ]
